apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: swap-provider-mongodb
spec:
  package: docker.io/svchaudharialliazn/swapnil-provider-mongodb:v0.1.9
  runtimeConfigRef:
    name: swap-provider-runtime
