apiVersion: mongodb.swapnil.io/v1alpha1
kind: ProviderConfig
metadata:
  name: vpc-provider
spec:
#  region: eu-central-1
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: mongodb-atlas-aws-creds
      key: credentials
