apiVersion: connectivity.mongodb.swapnil.io/v1alpha1
kind: VPCEndpoint
metadata:
  name: test-link
spec:
  forProvider:
    vpcId: vpc-03a75e9d856407da5
    serviceName: com.amazonaws.vpce.eu-central-1.vpce-svc-05eda7fee5676d6a3
    accountId: "198927051560"
    subnetIds:
    - subnet-000ff8403aca2347d
    securityGroupIds:
    - sg-0333847892bf56879
    region: eu-central-1
    ipAddressType: ipv4
    vpcEndpointType: Interface
  providerConfigRef:
    name: vpc-provider
