apiVersion: organization.mongodb.swapnil.io/v1alpha1
kind: Organization
metadata:
  name: swap-v19
spec:
  forProvider:
    ownerID: "68933765952cea244d470efb"
    apiKey:
      description: "Pure AWS organization API key - no Kubernetes secrets"
      roles:
        - "ORG_OWNER"
    awsSecretsConfig:
      region: "eu-central-1"
      secretName: "swap-v19"
      kmsKeyId: "arn:aws:kms:eu-central-1:198927051560:key/50aed21c-4e38-4e62-9907-f35911304563"
    networkAccessConfig:
      enabled: true
      autoCleanup: true
      apiAccessListRequired: true
      ips:
        - ip: "165.225.120.93"
        - ip: "167.103.3.4"
        - ip: "167.103.118.82"
  providerConfigRef:
    name: atlas-provider-aws-only
  deletionPolicy: Delete
  managementPolicies: ["*"]
